apiVersion: v2
type: application

# version and appVersion values are overrided during build step
version: 0.0.0
appVersion: 0.0.0

name: upgrade-manager-chart
description: Upgrade Manager Helm chart
home: https://github.com/qonto/upgrade-manager
sources:
  - https://github.com/qonto/upgrade-manager
annotations:
  artifacthub.io/category: integration-delivery
keywords:
  - argocd
  - upgrade
  - auto-discovery
