---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "upgrade-manager.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "upgrade-manager.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "upgrade-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml  . | nindent 8 }}
        {{- end }}
        checksum/config: {{ include (print .Template.BasePath "/config.yaml") . | sha256sum }}
      labels:
        {{- with .Values.podLabels }}
        {{- toYaml  . | nindent 8 }}
        {{- end }}
        {{- include "upgrade-manager.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "upgrade-manager.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      {{- with .Values.volumes }}
        {{- toYaml  . | nindent 8 }}
      {{- end }}
        - name: upgrade-manager-config
          configMap:
            name: {{ include "upgrade-manager.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          args:
            - "start"
            - "--config-file"
            - "{{ .Values.configFilePath }}"
            - "--log-format"
            - "{{ .Values.logFormat }}"
            - "--log-level"
            - "{{ .Values.logLevel }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.env }} 
          env:
            {{- toYaml  . | nindent 12 }}
          {{- end -}}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml  . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - mountPath: /app/config
              name: upgrade-manager-config
              readOnly: true
          {{- with .Values.volumeMounts }}
            {{- toYaml  . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
