{{ if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "upgrade-manager.fullname" . }}-role
  namespace: {{ .Release.Namespace | quote }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "upgrade-manager.fullname" . }}-cluster-role
rules:
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "upgrade-manager.fullname" . }}-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "upgrade-manager.fullname" . }}-cluster-role
subjects:
- kind: ServiceAccount
  name: {{ include "upgrade-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "upgrade-manager.fullname" . }}-role-binding
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "upgrade-manager.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "upgrade-manager.fullname" . }}
  namespace: upgrade-manager

{{- end -}}
