global:
  interval: wrong
  aws:
    region: eu-west-3
sources:
  argocdHelm:
    - enabled: true
      namespace: argocd
      filters:
        stabilityDays: 21 # minimum age for new releases to be considered stable (and add them as version candidates)
        skipPrerelease: true # skip pre-release versions (ex: 1.2.3-beta)
        skipFirstMajorVersion: true # skip major 0 versions (ex: 1.0.0, 2.0.0, 3.0.0 ...)
  filesystemHelm:
    - enabled: true
      paths:
        - "./internal/app/_testdata/test_chart/Chart.yaml"
        - "./internal/app/_testdata/test_chart2/Chart.yaml"
        - "./internal/app/_testdata/test_chart3/Chart.yaml"
        - "./internal/app/_testdata/test_chart4/Chart.yaml"
      filters:
        stabilityDays: 21
        skipPrerelease: true
        skipFirstMajorVersion: true
http:
  host: 0.0.0.0
  port: 10000
  write-timeout: 10
  read-timeout: 10
  read-header-timeout: 10
