{
 "title": "upgrade-manager",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(upgrade_manager_software_obsolescence_score{isparent=\"1\", action !=\"\"}, app)"
    }
   },
   {
    "name": "type",
    "label": "App Type",
    "query": {
     "query": "label_values(upgrade_manager_software_obsolescence_score, app_type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Per-App Metrics (app score >0)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$app",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "repeat": "app",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upgrade_manager_software_obsolescence_score{isparent=\"1\", app=~\"$app\", app_type=~\"$type\"}",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Upgrades to-do",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "upgrade_manager_software_obsolescence_score{parent=~\"$app\", action=\"update\", app_type=~\"$type\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Global metrics (all apps)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Tracked Applications",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upgrade_manager_total_software_found"
    }
   ]
  },
  {
   "title": "Average Obsolescence Score Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 5, "y": 17 },
   "targets": [
    {
     "expr": "sum(upgrade_manager_software_obsolescence_score{app=~\"$app\", isparent=\"1\"})/count(upgrade_manager_software_obsolescence_score{isparent=\"1\", app=~\"$app\"})",
     "legendFormat": "average score across selected apps"
    }
   ]
  },
  {
   "title": "Total obsolescence score",
   "type": "stat",
   "gridPos": { "h": 14, "w": 5, "x": 19, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(upgrade_manager_software_obsolescence_score{isparent=\"1\", app=~\"$app\"})"
    }
   ]
  },
  {
   "title": "App over score limit (100)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(upgrade_manager_software_obsolescence_score{isparent=\"1\"}>=100)"
    }
   ]
  },
  {
   "title": "Total Obsolescence Score over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 5, "y": 24 },
   "targets": [
    {
     "expr": "sum(upgrade_manager_software_obsolescence_score{isparent=\"1\"})",
     "legendFormat": "Total Sum of Obsolescence Score"
    }
   ]
  },
  { "title": "Health Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Tracked Applications",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upgrade_manager_total_software_found"
    }
   ]
  },
  {
   "title": "Processing Pipeline Success Milestones",
   "type": "bargauge",
   "description": "The 3 steps of the processing for an application.\nThe three values should be equal otherwise it means there is an error.",
   "gridPos": { "h": 5, "w": 10, "x": 5, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upgrade_manager_total_software_load_success",
     "legendFormat": "New Versions Discovery"
    },
    {
     "expr": "upgrade_manager_total_software_obsolescence_score_compute_success",
     "legendFormat": "Score Computation"
    }
   ]
  },
  {
   "title": "List of tracked softwares",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 32 },
   "targets": [
    {
     "expr": "upgrade_manager_software_obsolescence_score{isparent=\"1\"}"
    }
   ]
  },
  {
   "title": "App Processing Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upgrade_manager_software_process_error"
    }
   ]
  }
 ]
}